# Project information
site_name: nzb
site_author: Ravencentric
site_description: A spec compliant parser and meta editor for NZB files

# Repository
repo_name: nzb
repo_url: https://github.com/Ravencentric/nzb
edit_uri: edit/main/docs/

theme:
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  name: material
  font:
    text: Noto Sans
  palette:
      primary: black
      accent: light-blue
      scheme: slate
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - autorefs
  - mkdocstrings:
      enabled: true
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://typing-extensions.readthedocs.io/en/latest/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
          paths: [src]
          options:
            allow_inspection: false
            docstring_style: numpy
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            separate_signature: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            merge_init_into_class: true
            filters: ["!^_", "^__init__$"]

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - API Reference:
      - Parser: api-reference/parser.md
      - Meta Editor: api-reference/meta-editor.md
      - Models: api-reference/models.md
      - Types: api-reference/types.md
      - Exceptions: api-reference/exceptions.md
