name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release
    environment:
      name: release
      url: https://pypi.org/project/nzb/
    permissions:
      id-token: write
      contents: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for changelog

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"

      - name: Build
        run: uv build

      - name: Generate changelog with git-cliff
        uses: tj-actions/git-cliff@v1
        with:
          args: --latest --strip all
          template-config: .github/cliff-template.toml
          output: "CHANGELOG.md"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bodyFile: "CHANGELOG.md"
          draft: false
          prerelease: false

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

